// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCoN4cLjEv_Ays6g-ElTt3k9vCgOPRcs8',
    appId: '1:636088237611:web:c34cd26e3a43830f1bf46e',
    messagingSenderId: '636088237611',
    projectId: 'basic-calculator-karina',
    authDomain: 'basic-calculator-karina.firebaseapp.com',
    storageBucket: 'basic-calculator-karina.firebasestorage.app',
    measurementId: 'G-0G2HSBGVTE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADKskc3QKJU4irQjey7b57kQWJi56UxbI',
    appId: '1:636088237611:android:96ea9fcce202ab701bf46e',
    messagingSenderId: '636088237611',
    projectId: 'basic-calculator-karina',
    storageBucket: 'basic-calculator-karina.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHIF1sKylzUoyKq0_5oAjMiGQqNQ9Yl1g',
    appId: '1:636088237611:ios:f50f239d822ae5d21bf46e',
    messagingSenderId: '636088237611',
    projectId: 'basic-calculator-karina',
    storageBucket: 'basic-calculator-karina.firebasestorage.app',
    iosBundleId: 'com.example.basicCalculatorUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHIF1sKylzUoyKq0_5oAjMiGQqNQ9Yl1g',
    appId: '1:636088237611:ios:f50f239d822ae5d21bf46e',
    messagingSenderId: '636088237611',
    projectId: 'basic-calculator-karina',
    storageBucket: 'basic-calculator-karina.firebasestorage.app',
    iosBundleId: 'com.example.basicCalculatorUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCoN4cLjEv_Ays6g-ElTt3k9vCgOPRcs8',
    appId: '1:636088237611:web:43a20efd966677381bf46e',
    messagingSenderId: '636088237611',
    projectId: 'basic-calculator-karina',
    authDomain: 'basic-calculator-karina.firebaseapp.com',
    storageBucket: 'basic-calculator-karina.firebasestorage.app',
    measurementId: 'G-CW6YTXET34',
  );
}
